# Generated by Django 4.2 on 2023-05-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageenhance',
            name='filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
