# Generated by Django 4.2 on 2023-05-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_remove_imageenhance_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageenhance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='imageenhance',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
